maintainer       "Conjur Inc"
maintainer_email "ops@conjur.net"
name             "conjur-pam-ldap"
license          "All rights reserved"
description      "Installs/Configures Conjur PAM+LDAP"
version          "0.1.1"

depends   "conjur"
depends   "notifying-action"
supports  "ubuntu"
